name: mathy
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  random_color:
  provider: ^4.0.5+1
  firebase_auth:
  cloud_firestore:
  admob_flutter:
  audioplayers: ^0.15.1
  shared_preferences: ^0.5.7
  google_sign_in: ^4.4.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/auth_1.svg
    - images/auth_2.svg
    - images/auth_3.svg
    - images/auth_4.svg
    - images/brain.svg
    - images/facebook.svg
    - images/google.svg
    - images/menu.svg
    - images/bg.jpg
    - images/logo.svg
    - images/level.svg
    - images/sound.svg
    - images/share.svg

    - images/questions/lv1.svg
    - images/questions/lv2.svg
    - images/questions/lv3.svg
    - images/questions/lv4.svg
    - images/questions/lv5.svg
    - images/questions/lv6.svg
    - images/questions/lv7.svg
    - images/questions/lv8.svg
    - images/questions/lv9.svg
    - images/questions/lv10.svg
    - images/questions/lv11.svg
    - images/questions/lv12.svg
    - images/questions/lv13.svg
    - images/questions/lv14.png
    - images/questions/lv15.svg
    - images/questions/lv16.svg
    - images/questions/lv17.svg
    - images/questions/lv18.svg
    - images/questions/lv19.svg
    - images/questions/lv20.svg
    - images/questions/lv21.svg
    - images/questions/lv22.svg
    - images/questions/lv23.svg
    - images/questions/lv24.svg
    - images/questions/lv25.svg
    - images/questions/lv26.svg
    - images/questions/lv27.svg
    - images/questions/lv28.svg
    - images/questions/lv29.svg
    - images/questions/lv30.svg

    - images/questions/hint_lv1.svg
    - images/questions/hint_lv2.svg
    - images/questions/hint_lv3.svg
    - images/questions/hint_lv4.svg
    - images/questions/hint_lv5.svg
    - images/questions/hint_lv6.svg
    - images/questions/hint_lv7.svg
    - images/questions/hint_lv8.svg
    - images/questions/hint_lv9.svg
    - images/questions/hint_lv10.svg
    - images/questions/hint_lv11.svg
    - images/questions/hint_lv12.svg
    - images/questions/hint_lv13.svg
    - images/questions/hint_lv14.png
    - images/questions/hint_lv15.svg
    - images/questions/hint_lv16.svg
    - images/questions/hint_lv17.svg
    - images/questions/hint_lv18.svg
    - images/questions/hint_lv19.svg
    - images/questions/hint_lv20.svg
    - images/questions/hint_lv21.svg
    - images/questions/hint_lv22.svg
    - images/questions/hint_lv23.svg
    - images/questions/hint_lv24.svg
    - images/questions/hint_lv25.svg
    - images/questions/hint_lv26.svg
    - images/questions/hint_lv27.svg
    - images/questions/hint_lv28.svg
    - images/questions/hint_lv29.svg
    - images/questions/hint_lv30.svg

    - images/questions/solution_lv1.svg
    - images/questions/solution_lv2.svg
    - images/questions/solution_lv3.svg
    - images/questions/solution_lv4.svg
    - images/questions/solution_lv5.svg
    - images/questions/solution_lv6.svg
    - images/questions/solution_lv7.svg
    - images/questions/solution_lv8.svg
    - images/questions/solution_lv9.svg
    - images/questions/solution_lv10.svg
    - images/questions/solution_lv11.svg
    - images/questions/solution_lv12.svg
    - images/questions/solution_lv13.svg
    - images/questions/solution_lv14.png
    - images/questions/solution_lv15.svg
    - images/questions/solution_lv16.svg
    - images/questions/solution_lv17.svg
    - images/questions/solution_lv18.svg
    - images/questions/solution_lv19.svg
    - images/questions/solution_lv20.svg
    - images/questions/solution_lv21.svg
    - images/questions/solution_lv22.svg
    - images/questions/solution_lv23.svg
    - images/questions/solution_lv24.svg
    - images/questions/solution_lv25.svg
    - images/questions/solution_lv26.svg
    - images/questions/solution_lv27.svg
    - images/questions/solution_lv28.svg
    - images/questions/solution_lv29.svg
    - images/questions/solution_lv30.svg

    - assets/music/fearless.mp3
    - assets/music/happy.mp3
    - assets/music/epic.mp3
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mont
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
